# Generated by Django 3.1.5 on 2021-08-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.CharField(max_length=80, verbose_name='Email')),
                ('subject', models.CharField(max_length=80, verbose_name='Konu')),
                ('phone_n', models.IntegerField(max_length=11, verbose_name='Telefon')),
                ('message', models.CharField(max_length=288, verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
        ),
    ]
